<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 */

/**
 * Autoload
 */
$autoload_file = dirname(__FILE__) . '/vendor/autoload.php';
if (file_exists($env_config)) {
  require_once($autoload_file);
}
require_once(dirname(__FILE__) . '/config/application.php');
require_once(ABSPATH . 'wp-settings.php');
